/yolo_block_detector:
  ros__parameters:
    model_path: "src/robocom_vision/models/block_detector.pt"
    confidence_threshold: 0.5
    camera_id: 0

/color_mask_detector:
  ros__parameters:
    camera_id: 1

/depth_helper:
  ros__parameters:
    depth_stable_threshold: 0.005
    stable_frames: 10
